#!/usr/bin/env python3
"""Seed a Setlist vault with deterministic demo data.

Generates ~30 days of realistic-looking but fake logs across Nutrition,
Exercise, Habits, and Supplements. Used by the screenshot script and by
anyone running `npm run demo` to see the app with data before logging
their own.

Usage:
    python3 scripts/seed_demo_vault.py --vault examples/demo-vault/Bases
    python3 scripts/seed_demo_vault.py --vault /tmp/demo --today 2026-04-15 --days 45

The script is idempotent: running it again overwrites the Log/ folders
cleanly. It never touches files outside the target vault.
"""

from __future__ import annotations

import argparse
import random
import shutil
import sys
from dataclasses import dataclass
from datetime import date, datetime, timedelta
from pathlib import Path
from typing import Any

import yaml


@dataclass
class SeedConfig:
    vault: Path
    today: date
    days: int
    seed: int = 42


# ── Section writers ─────────────────────────────────────────────────────────

def _dump_frontmatter(fm: dict[str, Any]) -> str:
    body = yaml.safe_dump(fm, sort_keys=False, allow_unicode=True).strip()
    return f"---\n{body}\n---\n"


def _ensure_clean(dir_: Path) -> None:
    """Remove Log/ if it exists, then recreate empty. Preserves any
    sibling config files or .base files in the section folder."""
    if dir_.exists():
        shutil.rmtree(dir_)
    dir_.mkdir(parents=True, exist_ok=True)


def _write_config(path: Path, payload: dict[str, Any]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(
        "# Generated by scripts/seed_demo_vault.py — edit to taste.\n"
        + yaml.safe_dump(payload, sort_keys=False, allow_unicode=True)
    )


# ── Nutrition ───────────────────────────────────────────────────────────────

MEALS = [
    # (time, emoji, foods, macros=(p, f, c, kcal))
    ("07:45", "🍳", ["Breakfast", "3 eggs scrambled", "2 slices whole-wheat toast", "black coffee"], (28, 18, 36, 400)),
    ("08:00", "🥣", ["Breakfast", "Greek yogurt w/ berries", "honey + chia seeds", "espresso"], (22, 10, 42, 340)),
    ("07:30", "🥑", ["Breakfast", "Avocado toast", "2 poached eggs", "hot sauce"], (24, 22, 30, 420)),
    ("12:30", "🥗", ["Lunch", "Grilled chicken salad", "quinoa", "olive oil vinaigrette"], (42, 16, 48, 520)),
    ("13:00", "🍜", ["Lunch", "Ramen w/ soft egg", "bok choy", "chili oil"], (28, 18, 60, 560)),
    ("12:45", "🌯", ["Lunch", "Chicken burrito bowl", "brown rice + beans", "salsa verde"], (38, 14, 66, 560)),
    ("16:00", "🥜", ["Snack", "Peanut butter on apple"], (8, 16, 28, 260)),
    ("16:30", "🧀", ["Snack", "Cheese + crackers"], (10, 14, 20, 240)),
    ("19:30", "🍗", ["Dinner", "Oven chicken thighs", "roasted sweet potato", "steamed broccoli"], (44, 22, 52, 620)),
    ("20:00", "🐟", ["Dinner", "Pan-seared salmon", "wild rice", "asparagus"], (38, 20, 48, 560)),
    ("19:45", "🍝", ["Dinner", "Spaghetti bolognese", "parmesan", "mixed salad"], (34, 18, 72, 620)),
]


def seed_nutrition(cfg: SeedConfig) -> None:
    rnd = random.Random(cfg.seed)
    log_dir = cfg.vault / "Nutrition/Log"
    _ensure_clean(log_dir)

    # Pick 3 meals/day + ~40% of days get a snack, spread across 30 days.
    # Use disjoint pools so the same day doesn't repeat a meal.
    breakfasts = [m for m in MEALS if m[0].startswith("07") or m[0].startswith("08")]
    lunches    = [m for m in MEALS if m[0].startswith("12") or m[0].startswith("13")]
    snacks     = [m for m in MEALS if m[0].startswith("16")]
    dinners    = [m for m in MEALS if m[0].startswith("19") or m[0].startswith("20")]

    for offset in range(cfg.days):
        day = cfg.today - timedelta(days=offset)
        todays = [rnd.choice(breakfasts), rnd.choice(lunches), rnd.choice(dinners)]
        if rnd.random() < 0.4:
            todays.append(rnd.choice(snacks))
        todays.sort(key=lambda m: m[0])

        for i, (time_str, emoji, foods, (p, f, c, k)) in enumerate(todays, start=1):
            # Small per-entry jitter so charts aren't flat.
            jitter = lambda v: max(0, int(v * (0.85 + rnd.random() * 0.3)))
            fm = {
                "date": day.isoformat(),
                "time": time_str,
                "emoji": emoji,
                "protein_g": jitter(p),
                "fat_g": jitter(f),
                "carbs_g": jitter(c),
                "kcal": jitter(k),
                "foods": foods,
                "section": "nutrition",
            }
            fname = f"{day.isoformat()}--{time_str.replace(':', '')}--{i:02d}.md"
            (log_dir / fname).write_text(_dump_frontmatter(fm))


# ── Exercise ────────────────────────────────────────────────────────────────

UPPER_DAY = [
    ("elliptical", {"duration_min": 10, "distance_m": 1500, "level": 7}),
    ("rowing",     {"duration_min": 10, "distance_m": 1900, "level": 2}),
    ("chest press",         {"weight": 35.0, "sets": 3, "reps": 12}),
    ("diverging seated row",{"weight": 40.0, "sets": 3, "reps": 12}),
    ("lat pull",            {"weight": 45.0, "sets": 3, "reps": 12}),
    ("shoulder press",      {"weight": 22.5, "sets": 3, "reps": 10}),
    ("triceps extension",   {"weight": 25.0, "sets": 3, "reps": 12}),
    ("biceps",              {"weight": 20.0, "sets": 3, "reps": 12}),
    ("ab crunch",           {"weight": 30.0, "sets": 3, "reps": 15}),
]

LOWER_DAY = [
    ("elliptical", {"duration_min": 10, "distance_m": 1500, "level": 7}),
    ("rowing",     {"duration_min": 10, "distance_m": 1900, "level": 2}),
    ("leg press",      {"weight": 85.0, "sets": 3, "reps": 12}),
    ("leg extension",  {"weight": 50.0, "sets": 3, "reps": 12}),
    ("leg curl",       {"weight": 45.0, "sets": 3, "reps": 12}),
    ("abduction",      {"weight": 40.0, "sets": 3, "reps": 15}),
    ("adduction",      {"weight": 40.0, "sets": 3, "reps": 15}),
    ("calf press",     {"weight": 100.0, "sets": 3, "reps": 15}),
    ("ab crunch",      {"weight": 30.0, "sets": 3, "reps": 15}),
]

CARDIO_DAY = [
    ("elliptical", {"duration_min": 30, "distance_m": 4200, "level": 4}),
    ("rowing",     {"duration_min": 20, "distance_m": 3600, "level": 1}),
]

DAY_ROTATION = [UPPER_DAY, CARDIO_DAY, LOWER_DAY, CARDIO_DAY]  # 4-day cycle


def seed_exercise(cfg: SeedConfig) -> None:
    rnd = random.Random(cfg.seed + 1)
    log_dir = cfg.vault / "Exercise/Log"
    _ensure_clean(log_dir)

    # One session every other day (so ~15 over 30 days)
    for offset in range(0, cfg.days, 2):
        day = cfg.today - timedelta(days=offset)
        template = DAY_ROTATION[offset // 2 % len(DAY_ROTATION)]
        concluded = datetime.combine(day, datetime.min.time()).replace(hour=8, minute=rnd.randint(0, 30))

        for slug, fields in template:
            fm: dict[str, Any] = {
                "date": day.isoformat(),
                "exercise": slug,
                "concluded_at": concluded.isoformat(timespec="seconds"),
            }
            # Gentle progression: +0.5kg per week on strength
            for k, v in fields.items():
                if k == "weight" and isinstance(v, float):
                    weeks_back = offset // 7
                    v = round(v - weeks_back * 0.5, 1)
                fm[k] = v
            fm["difficulty"] = rnd.choice(["easy", "medium", "medium", "hard"])

            fname = f"{day.isoformat()}--{slug.replace(' ', '-')}--01.md"
            (log_dir / fname).write_text(_dump_frontmatter(fm))


# ── Habits ──────────────────────────────────────────────────────────────────

HABITS_CONFIG = {
    "habits": [
        {"id": "meditation",         "name": "Meditation 10min", "bucket": "morning"},
        {"id": "brush-teeth-morning","name": "Brush teeth",       "bucket": "morning"},
        {"id": "walk",               "name": "Walk outside",      "bucket": "afternoon"},
        {"id": "stretch",            "name": "10min stretch",     "bucket": "evening"},
        {"id": "brush-teeth-evening","name": "Brush teeth",       "bucket": "evening"},
    ]
}


def seed_habits(cfg: SeedConfig) -> None:
    rnd = random.Random(cfg.seed + 2)
    section = cfg.vault / "Habits"
    log_dir = section / "Log"
    _ensure_clean(log_dir)
    _write_config(section / "habits-config.yaml", HABITS_CONFIG)

    for offset in range(cfg.days):
        day = cfg.today - timedelta(days=offset)
        # Skip roughly 20% of habits per day so the streak chart has variation.
        for h in HABITS_CONFIG["habits"]:
            if rnd.random() < 0.2:
                continue
            fm = {
                "date": day.isoformat(),
                "id": f"habit-{day.isoformat()}-{h['id']}",
                "section": "habits",
                "habit_id": h["id"],
                "habit_name": h["name"],
                "bucket": h["bucket"],
                "note": None,
            }
            fname = f"{day.isoformat()}--{h['id']}--01.md"
            (log_dir / fname).write_text(_dump_frontmatter(fm))


# ── Supplements ─────────────────────────────────────────────────────────────

SUPPLEMENTS_CONFIG = {
    "supplements": [
        {"id": "omega3",       "name": "Omega-3",     "emoji": "🐟"},
        {"id": "creatine",     "name": "Creatine 5g", "emoji": "💪"},
        {"id": "vitamin-d",    "name": "Vitamin D",   "emoji": "☀️"},
        {"id": "magnesium",    "name": "Magnesium",   "emoji": "🌙"},
    ]
}


def seed_supplements(cfg: SeedConfig) -> None:
    rnd = random.Random(cfg.seed + 3)
    section = cfg.vault / "Supplements"
    log_dir = section / "Log"
    _ensure_clean(log_dir)
    _write_config(section / "supplements-config.yaml", SUPPLEMENTS_CONFIG)

    for offset in range(cfg.days):
        day = cfg.today - timedelta(days=offset)
        for s in SUPPLEMENTS_CONFIG["supplements"]:
            if rnd.random() < 0.15:
                continue
            fm = {
                "date": day.isoformat(),
                "id": f"supplement-{day.isoformat()}-{s['id']}",
                "section": "supplements",
                "supplement_id": s["id"],
                "supplement_name": s["name"],
                "emoji": s["emoji"],
                "note": None,
            }
            fname = f"{day.isoformat()}--{s['id']}--01.md"
            (log_dir / fname).write_text(_dump_frontmatter(fm))


# ── Caffeine ────────────────────────────────────────────────────────────────

CAFFEINE_BEANS = [
    {"id": "ethiopia-yirgacheffe", "name": "Ethiopia Yirgacheffe"},
    {"id": "colombia-huila",       "name": "Colombia Huila"},
    {"id": "kenya-nyeri",          "name": "Kenya Nyeri"},
]

# (time, method, grams, beans_id-or-None)
CAFFEINE_DRINKS = [
    ("07:30", "v60",    14, "ethiopia-yirgacheffe"),
    ("08:00", "v60",    15, "colombia-huila"),
    ("08:15", "v60",    14, "kenya-nyeri"),
    ("10:30", "matcha",  2, None),
    ("13:15", "v60",    12, "colombia-huila"),
    ("15:30", "matcha",  2, None),
]


def seed_caffeine(cfg: SeedConfig) -> None:
    rnd = random.Random(cfg.seed + 4)
    section = cfg.vault / "Caffeine"
    log_dir = section / "Log"
    _ensure_clean(log_dir)
    _write_config(section / "caffeine-config.yaml", {"beans": CAFFEINE_BEANS})

    for offset in range(cfg.days):
        day = cfg.today - timedelta(days=offset)
        # 1–3 drinks/day, biased toward morning
        n = rnd.choices([1, 2, 3], weights=[2, 4, 2])[0]
        picks = rnd.sample(CAFFEINE_DRINKS, k=n)
        picks.sort(key=lambda d: d[0])
        counters: dict[str, int] = {}
        for time_str, method, grams, beans_id in picks:
            counters[method] = counters.get(method, 0) + 1
            nn = counters[method]
            fm = {
                "date": day.isoformat(),
                "time": time_str,
                "id": f"caffeine-{day.isoformat()}-{method}-{nn:02d}",
                "section": "caffeine",
                "method": method,
                "beans": beans_id,
                "grams": grams,
                "note": None,
            }
            fname = f"{day.isoformat()}--{method}--{nn:02d}.md"
            (log_dir / fname).write_text(_dump_frontmatter(fm))


# ── Chores ──────────────────────────────────────────────────────────────────

CHORES_DEFS = [
    {"id": "dishes",       "name": "Dishes",            "cadence_days": 1,  "emoji": "🍽️"},
    {"id": "laundry",      "name": "Laundry",           "cadence_days": 7,  "emoji": "🧺"},
    {"id": "vacuum",       "name": "Vacuum",            "cadence_days": 7,  "emoji": "🧹"},
    {"id": "trash",        "name": "Take out trash",    "cadence_days": 3,  "emoji": "🗑️"},
    {"id": "plants",       "name": "Water plants",      "cadence_days": 4,  "emoji": "🪴"},
    {"id": "sheets",       "name": "Change sheets",     "cadence_days": 14, "emoji": "🛏️"},
    {"id": "bathroom",     "name": "Clean bathroom",    "cadence_days": 7,  "emoji": "🛁"},
]


def seed_chores(cfg: SeedConfig) -> None:
    rnd = random.Random(cfg.seed + 5)
    section = cfg.vault / "Chores"
    defs_dir = section / "Definitions"
    log_dir = section / "Log"
    _ensure_clean(defs_dir)
    _ensure_clean(log_dir)

    # Definitions: one note per chore.
    for c in CHORES_DEFS:
        fm = {
            "id": c["id"],
            "name": c["name"],
            "cadence_days": c["cadence_days"],
            "emoji": c["emoji"],
            "section": "chores",
        }
        (defs_dir / f"{c['id']}.md").write_text(_dump_frontmatter(fm))

    # Completions: walk forward from earliest date, simulate each chore
    # being completed at (roughly) its cadence. Skip occasional cadences
    # so a few chores land overdue today.
    for c in CHORES_DEFS:
        # Start N days ago so the most recent completion lands ~1 cadence
        # before today (half the chores overdue, half fresh).
        skew = rnd.randint(0, c["cadence_days"])
        current = cfg.today - timedelta(days=cfg.days - 1) + timedelta(days=skew)
        while current <= cfg.today:
            # 10% chance to skip this completion — nobody's perfect.
            if rnd.random() >= 0.1:
                fm = {
                    "date": current,
                    "time": f"{rnd.randint(7, 21):02d}:{rnd.randint(0, 59):02d}",
                    "id": f"chore-{current.isoformat()}-{c['id']}-complete",
                    "section": "chores",
                    "chore_id": c["id"],
                    "chore_name": c["name"],
                    "action": "complete",
                }
                fname = f"{current.isoformat()}--{c['id']}--complete.md"
                (log_dir / fname).write_text(_dump_frontmatter(fm))
            # Jitter the cadence so the history chart isn't uniform.
            jitter = rnd.randint(-1, 1) if c["cadence_days"] > 1 else 0
            current += timedelta(days=max(1, c["cadence_days"] + jitter))


# ── Settings + macros ───────────────────────────────────────────────────────

def seed_settings_and_macros(cfg: SeedConfig) -> None:
    _write_config(cfg.vault / "Nutrition/macros-config.yaml", {
        "targets": {
            "protein": {"min": 100, "max": 150, "unit": "g"},
            "fat":     {"min": 50,  "max": 80,  "unit": "g"},
            "carbs":   {"min": 200, "max": 300, "unit": "g"},
            "kcal":    {"min": 2000, "max": 2500, "unit": ""},
        }
    })
    _write_config(cfg.vault / "Settings/settings.yaml", {
        "section_order": [
            "exercise", "nutrition", "habits", "supplements",
            "chores", "caffeine", "sleep", "body", "health",
        ],
        # Demo vault has no data for these — hide from nav + home grid so
        # screenshots don't include empty tiles. Sleep/body/health are fed
        # by a pre-seeded health-cache.json (see seed_demo_health).
        "sections": {
            "groceries": {"enabled": False},
            "cannabis":  {"enabled": False},
        },
        "animations": {"first_meal": True, "histograms_raise": True},
    })


# ── Main ────────────────────────────────────────────────────────────────────

def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--vault", required=True, type=Path,
                        help="Target Bases/ directory (will be created if missing)")
    parser.add_argument("--today", default=None,
                        help="Override 'today' as YYYY-MM-DD (default: actual today)")
    parser.add_argument("--days", type=int, default=30,
                        help="How many days back to seed (default: 30)")
    args = parser.parse_args()

    today = (
        datetime.strptime(args.today, "%Y-%m-%d").date()
        if args.today else date.today()
    )
    cfg = SeedConfig(vault=args.vault.resolve(), today=today, days=args.days)

    # Guard: don't overwrite a real vault by accident. Drop a marker on
    # first seed; subsequent runs see the marker and skip the size check.
    marker = cfg.vault / ".setlist-demo-vault"
    if not marker.exists():
        for log in cfg.vault.rglob("Log"):
            if log.is_dir() and sum(1 for _ in log.iterdir()) > 50:
                print(
                    f"ERROR: {log} has >50 files and no .setlist-demo-vault marker\n"
                    f"— this looks like a real vault. If you're sure, delete {log}\n"
                    f"or pass --vault pointing at a dedicated demo directory.",
                    file=sys.stderr,
                )
                return 1

    print(f"Seeding demo vault at {cfg.vault}")
    print(f"  today={cfg.today.isoformat()}  days={cfg.days}")

    cfg.vault.mkdir(parents=True, exist_ok=True)
    marker.write_text("Marker file — indicates this vault was seeded by scripts/seed_demo_vault.py. Safe to delete.\n")
    seed_nutrition(cfg)
    seed_exercise(cfg)
    seed_habits(cfg)
    seed_supplements(cfg)
    seed_caffeine(cfg)
    seed_chores(cfg)
    seed_settings_and_macros(cfg)

    print("Done.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
